package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentAllPropertiesEquals(Parent expected, Parent actual) {
        assertParentAutoGeneratedPropertiesEquals(expected, actual);
        assertParentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentAllUpdatablePropertiesEquals(Parent expected, Parent actual) {
        assertParentUpdatableFieldsEquals(expected, actual);
        assertParentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentAutoGeneratedPropertiesEquals(Parent expected, Parent actual) {
        assertThat(expected)
            .as("Verify Parent auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentUpdatableFieldsEquals(Parent expected, Parent actual) {
        assertThat(expected)
            .as("Verify Parent relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParentUpdatableRelationshipsEquals(Parent expected, Parent actual) {}
}
